var kjvBooks = {
	"Gen": "Genesis",
	"Exod": "Exodus",
	"Lev": "Leviticus",
	"Num": "Numbers",
	"Deut": "Deuteronomy",
	"Josh": "Joshua",
	"Judg": "Judges",
	"Ruth": "Ruth",
	"1Sam": "1 Samuel",
	"2Sam": "2 Samuel",
	"1Kgs": "1 Kings",
	"2Kgs": "2 Kings",
	"1Chr": "1 Chronicles",
	"2Chr": "2 Chronicles",
	"Ezra": "Ezra",
	"Neh": "Nehemiah",
	"Esth": "Esther",
	"Job": "Job",
	"Ps": "Psalms",
	"Prov": "Proverbs",
	"Eccl": "Ecclesiastes",
	"Song": "Song of Solomon",
	"Isa": "Isaiah",
	"Jer": "Jeremiah",
	"Lam": "Lamentations",
	"Ezek": "Ezekiel",
	"Dan": "Daniel",
	"Hos": "Hosea",
	"Joel": "Joel",
	"Amos": "Amos",
	"Obad": "Obadiah",
	"Jonah": "Jonah",
	"Mic": "Micah",
	"Nah": "Nahum",
	"Hab": "Habakkuk",
	"Zeph": "Zephaniah",
	"Hag": "Haggai",
	"Zech": "Zechariah",
	"Mal": "Malachi",
	"Matt": "Matthew",
	"Mark": "Mark",
	"Luke": "Luke",
	"John": "John",
	"Acts": "Acts",
	"Rom": "Romans",
	"1Cor": "1 Corinthians",
	"2Cor": "2 Corinthians",
	"Gal": "Galatians",
	"Eph": "Ephesians",
	"Phil": "Philippians",
	"Col": "Colossians",
	"1Thess": "1 Thessalonians",
	"2Thess": "2 Thessalonian",
	"1Tim": "1 Timothy",
	"2Tim": "2 Timothy",
	"Titus": "Titus",
	"Phlm": "Philemon",
	"Heb": "Hebrews",
	"Jas": "James",
	"1Pet": "1 Peter",
	"2Pet": "2 Peter",
	"1John": "1 John",
	"2John": "2 John",
	"3John": "3 John",
	"Jude": "Jude",
	"Rev": "Revelation"
}

var tbBooks = {
	"1": "Genesis",
	"2": "Exodus",
	"3": "Leviticus",
	"4": "Numbers",
	"5": "Deuteronomy",
	"6": "Joshua",
	"7": "Judges",
	"8": "Ruth",
	"9": "1 Samuel",
	"10": "2 Samuel",
	"11": "1 Kings",
	"12": "2 Kings",
	"13": "1 Chronicles",
	"14": "2 Chronicles",
	"15": "Ezra",
	"16": "Nehemiah",
	"17": "Esther",
	"18": "Job",
	"19": "Psalms",
	"20": "Proverbs",
	"21": "Ecclesiastes",
	"22": "Song of Solomon",
	"23": "Isaiah",
	"24": "Jeremiah",
	"25": "Lamentations",
	"26": "Ezekiel",
	"27": "Daniel",
	"28": "Hosea",
	"29": "Joel",
	"30": "Amos",
	"31": "Obadiah",
	"32": "Jonah",
	"33": "Micah",
	"34": "Nahum",
	"35": "Habakkuk",
	"36": "Zephaniah",
	"37": "Haggai",
	"38": "Zechariah",
	"39": "Malachi",
	"40": "Matthew",
	"41": "Mark",
	"42": "Luke",
	"43": "John",
	"44": "Acts",
	"45": "Romans",
	"46": "1 Corinthians",
	"47": "2 Corinthians",
	"48": "Galatians",
	"49": "Ephesians",
	"50": "Philippians",
	"51": "Colossians",
	"52": "1 Thessalonians",
	"53": "2 Thessalonian",
	"54": "1 Timothy",
	"55": "2 Timothy",
	"56": "Titus",
	"57": "Philemon",
	"58": "Hebrews",
	"59": "James",
	"60": "1 Peter",
	"61": "2 Peter",
	"62": "1 John",
	"63": "2 John",
	"64": "3 John",
	"65": "Jude",
	"66": "Revelation"
}